--flagfile=/apollo/modules/common/data/global_flagfile.txt
--map_dir=/apollo/modules/map/data/yunle_indoor_map03_planning
--base_map_filename=base_map.bin|base_map.txt
--routing_response_topic=/apollo/routing_response
