# --freq_checker_name="Channel Freq"

# report interval in ms
# --freq_report_interval=100

# default filter rule: 3/3
# --freq_filter_required_cycles=3
# --freq_filter_total_cycles=3

# default fault removed secs
# --freq_removed_secs=10