# control checker name
#--control_checker_name="Control"

# reader message expired seconds, expired message will be ignored.
# default: 1.0
#--chassis_msg_expired_sec=1.0

# gear inconsistency seconds threshold
# when gear not match start to record duration,
# duration above threshold the gear will be considered inconsistency.
# default: 2.0
#--gear_inconsistency_sec_threshold=2.0

# throttle inconsistency threshold percentage
# when throttle diff is above threshold, start to record duration.
# default: 5.0
#--throttle_inconsistency_threshold=5.0

# throttle failure seconds threshold
# duration above threshold throttle is considered failure.
# default: 2.0
#--throttle_failure_sec_threshold=2.0


# brake inconsistency threshold percentage
# when brake diff is above threshold, start to record duration.
# default: 5.0
#--brake_inconsistency_threshold=5.0

# brake failure seconds threshold
# duration above threshold brake is considered failure.
# default: 1.0
#--brake_failure_sec_threshold=1.0

# brake check speed limit in m/s
# speed is below the limit the brake would not be checked.
# default: 0.5
#--brake_check_speed_limit=0.5


# steer inconsistency threshold percentage
# when steer diff is above threshold, start to record duration.
# default: 5.0
#--steer_inconsistency_threshold=5.0

# steer failure seconds threshold
# duration above threshold steer is considered failure.
# default: 2.0
#--steer_failure_sec_threshold=2.0


# sliding speed threshold in m/s
# when gear is neutral and speed is above limit, start to record duration.
# default: 0.5
#--sliding_speed_threshold=0.5

# sliding accident seconds threshold
# duration above threshold, sliding accident is happening.
# default: 2.0
#--steer_failure_sec_threshold=2.0


# speed inconsistency threshold percentage
# when speed diff is above threshold, start to record duration.
# default: 50
#--speed_inconsistency_threshold_percentage=50

# speed inconsistency seconds threshold
# duration above threshold speed is considered inconsistency.
# default: 1.0
#--speed_inconsistency_sec_threshold=1.0

# speed percentage check limit in m/s
# speed is below limit, no check speed percentage to avoid mistakes.
# default: 10
#--speed_percentage_check_limit=3


# control 控制误差报警
# 纵向位置误差
#--lon_station_error_warn_threshold=2.0
#--lon_station_error_error_threshold=3.0

# 纵向速度误差
#--lon_speed_error_warn_threshold=1.5
#--lon_speed_error_error_threshold=2.0

# 横向位置误差
#--lat_lateral_error_warn_threshold=0.3
#--lat_lateral_error_error_threshold=0.5

# 横向航向角误差
#--lat_heading_error_warn_threshold=0.3
#--lat_heading_error_error_threshold=0.5

# 规划曲率超限
#--lat_curvature_warn_times=1
#--lat_curvature_error_times=5