# localization checker name
#--localization_checker_name="Localization"

# The safety status fatal threshold, when the localization status value is
# greater than the threshold, set safety status to fatal. Only used in the
# following status, and the values of these status is following:
# MeasureState::ERROR: 1
# MeasureState::CRITICAL_ERROR: 2
# MeasureState::FATAL_ERROR: 3
# default fatal threshold: 3
#--safety_status_fatal_threshold=3

# default localization item code
# --localization_item_code=3005001

# default fault removed secs
# --localization_removed_secs=10