--flagfile=/apollo/modules/common/data/global_flagfile.txt
--traffic_rule_config_filename=/apollo/modules/planning/planning_component/conf/traffic_rule_config.pb.txt
--planning_upper_speed_limit=2.0
--default_cruise_speed=1.5
--ignore_overlapped_obstacle=true
--prioritize_change_lane
--min_length_for_lane_change=5.0
--nouse_multi_thread_to_add_obstacles
# --min_past_history_points_len=10
--enable_print_curve=true
--destination_check_distance=4.0
# --smoother_config_filename=/apollo/modules/planning/planning_component/conf/spiral_smoother_config.pb.txt
# --smoother_config_filename=/apollo/modules/planning/planning_component/conf/qp_spline_smoother_config.pb.txt
--smoother_config_filename=/apollo/modules/planning/planning_component/conf/discrete_points_smoother_config.pb.txt
--enable_reference_line_stitching=false
--speed_bump_speed_limit=1.5
# --parking_inwards=false
# --use_dual_variable_warm_start=true
# --enable_record_debug=true
# --enable_parallel_hybrid_a=true
--export_chart=true
--longitudinal_jerk_lower_bound=-10
--longitudinal_jerk_upper_bound=10
# --use_front_axe_center_in_path_planning=true
--obstacle_lat_buffer=0.4
--min_stop_distance_obstacle=1.5
--static_obstacle_nudge_l_buffer=0.6
--enable_smoother_failsafe
--enable_parallel_trajectory_smoothing=true
--use_s_curve_speed_smooth
--use_iterative_anchoring_smoother=true
--speed_fallback_distance=0.0
--nonstatic_obstacle_nudge_l_buffer=0.15

--use_st_drivable_boundary=false

--enable_pull_over_at_destination=false

--replan_time_threshold=7.0
--obstacle_lon_start_buffer=0.4
--check_collision_freespace_obstacle_vertices=false
--yield_distance=1.0
--passed_destination_threshold=0.5

--open_space_delta_t=0.2
--open_space_acc_weight=1.0
--open_space_jerk_weight=10.0
--open_space_kappa_weight=100.0
--open_space_reference_s_weight=10.0
--open_space_reference_v_weight=10.0
--open_space_max_forward_v=0.3
--open_space_max_reverse_v=0.3
--open_space_max_forward_acc=1.0
--open_space_max_reverse_acc=0.3
--open_space_max_jerk=2.0

--enable_reference_line_provider_thread=false

--enable_smooth_reference_line=true
--enable_corner_constraint=true
--enable_expand_obs_corner=false
--enable_adc_vertex_constraint=true