--flagfile=/apollo/modules/common/data/global_flagfile.txt
--flagfile=/apollo/modules/slam_local/conf/slam_local.flag

# topic list
--location_lidar_topic=liorf/mapping/odometry_slam_with_status
--imu_raw_topic=/apollo/sensor/gnss/imu
--gnss_bestpose_topic=/apollo/sensor/gnss/best_pose
--measure_data_topic=/apollo/localization/intergrate/measure_data
--heading_msg_topic=/apollo/sensor/gnss/heading
--odometry_msg_topic=/apollo/sensor/gnss/odometry
--canbus_msg_topic=/apollo/canbus/chassis
--integrate_status_topic=/apollo/localization/fusion_status

# if gnss bad, init from local inspva data
# Attention: only if you have canbus_msg_topic can this work, millisecond
--if_init_from_inspva_history_data=true
--init_align_time_out_threshold=120000
--init_double_check_time_out_threshold=30000

# threshold for timestamp diff
# [default 0.21] if integ measure update failed, set value according to diff
--measure_sins_timestamp_diff=0
# [haijia 0.05;kjy 0.02] if Drop measure data, set value according to diff
--measure_imu_timestamp_diff=0
# [haijia 0.14;kjy 0.0] if Yaw align failed, change to 0.0, set value according to diff
--measure_heading_timestamp_diff=0

--is_use_gnss_cov=true
--is_use_kalman=true

# good gnss position type list, only this can be add to kalman
--good_gnss_position_type=48,49,50,56

# threshold for kalman fusiton status, meter
--sol_fusion_loc_std_x_threshold=0.08
--sol_fusion_loc_std_y_threshold=0.08
--sol_fusion_heading_std_threshold=0.25
--ssol_fusion_loc_std_x_threshold=0.12
--ssol_fusion_loc_std_y_threshold=0.12
--msf_sol_count_threshold=3000

# level arm, imu coord, rear right to imu, meter
--imu_wheelspeed_rear_right_arm_x=0.505
--imu_wheelspeed_rear_right_arm_y=-0.778
--imu_wheelspeed_rear_right_arm_z=0.05

--lidar_good_num_count_for_init_success=10
--loc_std_x_threshold_for_init_success=0.10
--loc_std_y_threshold_for_init_success=0.10

# safety manager
#### 1105307
--lon_station_error_warn_threshold=0.15
--lon_station_error_error_threshold=0.30
--lat_station_error_warn_threshold=0.10
--lat_station_error_error_threshold=0.25
#### 1105308
--lon_speed_error_warn_threshold=0.15
--lon_speed_error_error_threshold=0.3
--lat_speed_error_warn_threshold=0.25
--lat_speed_error_error_threshold=0.5
#### 1105306
--vn_sins_speed_error_warn_threshold=0.1
--vn_sins_speed_error_error_threshold=0.2
--ve_sins_speed_error_warn_threshold=0.1
--ve_sins_speed_error_error_threshold=0.2