#include <fstream>
#include <iostream>
#include <string>

#include "gflags/gflags.h"
#include "nlohmann/json.hpp"

#include "cyber/common/file.h"
#include "modules/map_creator/map_tool/common/map_tool_gflags.h"
#include "modules/map_creator/map_tool/converter.h"

DEFINE_string(input_json, "", "Path to EditorMap json file generated by map_editor_frontend.");
DEFINE_string(output_dir, "", "Directory to store released Apollo HDMap files.");
DEFINE_string(base_map_dir, "", "Path to the current base map directory (used for dumping local_map).");
DEFINE_bool(skip_validate, false, "Skip map validity check before releasing.");

namespace {

constexpr const char* kValidationReport = "validation_report.json";
constexpr const char* kEditorMapBackup = "editor_map.json";

void PrintUsage() {
  std::cerr << "Usage:\n"
            << "  editor_map_converter "
            << "--input_json=/path/to/map.json "
            << "--output_dir=/path/to/output "
            << "[--base_map_dir=/path/to/base_map] "
            << "[--skip_validate=true]\n";
}

apollo::map_tool::Status ConvertJsonToHdMap(
    const nlohmann::json& json_data,
    apollo::hdmap::Map* hd_map) {
  return apollo::map_tool::ConvertToApolloMap(json_data, hd_map);
}

bool DumpValidationReport(const std::string& output_dir,
                          const nlohmann::json& report) {
  try {
    std::ofstream ofs(output_dir + "/" + kValidationReport);
    ofs << report.dump(2);
    ofs.close();
  } catch (const std::exception& e) {
    std::cerr << "Failed to write validation report: " << e.what() << std::endl;
    return false;
  }
  return true;
}

bool BackupEditorMapJson(const std::string& output_dir,
                         const std::string& json_path) {
  try {
    std::string content;
    if (!apollo::cyber::common::GetContent(json_path, &content)) {
      return false;
    }
    std::ofstream ofs(output_dir + "/" + kEditorMapBackup);
    ofs << content;
    ofs.close();
    return true;
  } catch (const std::exception& e) {
    std::cerr << "Failed to backup editor map json: " << e.what() << std::endl;
    return false;
  }
}

}  // namespace

int main(int argc, char** argv) {
  google::ParseCommandLineFlags(&argc, &argv, true);

  if (FLAGS_input_json.empty() || FLAGS_output_dir.empty()) {
    PrintUsage();
    return -1;
  }

  if (!apollo::cyber::common::PathExists(FLAGS_input_json)) {
    std::cerr << "Input json not found: " << FLAGS_input_json << std::endl;
    return -1;
  }

  if (!apollo::cyber::common::EnsureDirectory(FLAGS_output_dir)) {
    std::cerr << "Unable to create output directory: " << FLAGS_output_dir
              << std::endl;
    return -1;
  }

  if (!FLAGS_base_map_dir.empty()) {
    FLAGS_curr_base_map_dir = FLAGS_base_map_dir;
  }

  std::string json_content;
  if (!apollo::cyber::common::GetContent(FLAGS_input_json, &json_content)) {
    std::cerr << "Failed to read json file: " << FLAGS_input_json << std::endl;
    return -1;
  }

  nlohmann::json json_data;
  try {
    json_data = nlohmann::json::parse(json_content);
  } catch (const std::exception& e) {
    std::cerr << "Invalid json content: " << e.what() << std::endl;
    return -1;
  }

  apollo::hdmap::Map hd_map;
  auto status = ConvertJsonToHdMap(json_data, &hd_map);
  if (status.code != apollo::map_tool::Code::OK) {
    std::cerr << "ConvertToApolloMap failed: " << status.message << std::endl;
    return -1;
  }

  nlohmann::json validation_report;
  if (!FLAGS_skip_validate &&
      !apollo::map_tool::MapValidityCheck(hd_map, &validation_report)) {
    if (!validation_report.is_null() && !validation_report.empty()) {
      DumpValidationReport(FLAGS_output_dir, validation_report);
      std::cerr << "Map validity check failed. "
                << "See validation_report.json for details." << std::endl;
    } else {
      std::cerr << "Map validity check failed." << std::endl;
    }
    return -2;
  }

  if (!FLAGS_skip_validate && !validation_report.is_null() &&
      !validation_report.empty()) {
    DumpValidationReport(FLAGS_output_dir, validation_report);
  }

  auto release_status =
      apollo::map_tool::ReleaseApolloMap(FLAGS_output_dir, hd_map);
  if (release_status.code != apollo::map_tool::Code::OK) {
    std::cerr << "ReleaseApolloMap failed: " << release_status.message
              << std::endl;
    return -1;
  }

  BackupEditorMapJson(FLAGS_output_dir, FLAGS_input_json);

  std::cout << "Editor map published to: " << FLAGS_output_dir << std::endl;
  if (!FLAGS_base_map_dir.empty()) {
    std::cout << "Base map directory: " << FLAGS_base_map_dir << std::endl;
  }
  return 0;
}
