# ms, emit decision result for this time interval
--decider_period = 1000

# ms, emit aggregator result for this time interval
--aggregator_period = 2000

# seconds, item over this second will be removed from aggregator status array
--aggregator_reserved_sec = 10.0