load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "yunle_chassis_receiver_proto",
    srcs = ["yunle_chassis_receiver.proto"],
)

apollo_package()
