# collision checker name
#--collision_checker_name="Collision"

# default collision checker item code
# --collision_item_code=5000001

# reader message expired seconds, expired message will be ignored.
# default: 1.0
#--msg_expired_sec=1.0

# ttc calculate interval in seconds.
# default: 0.1
#--ttc_calculate_interval_sec=0.1

# ttc calculating only in auto driving mode
# default: true
# --only_on_auto_driving_mode=true

# read obstacles from perception topic
# default: false
# --obstacle_from_perception_topic=false

# ttc debug channel, using for debug ttc program.
#--ttc_debug_topic="/apollo/safety/ttc_debug"

# if using debug mode, debug info will be written into ttc_debug_topic channel.
--ttc_debug_mode=true

# default filter: 3/3
# --collision_checker_required_cycles=3
# --collision_checker_total_cycles=3

# default fault removed secs
# --collision_fault_removed_secs=3