# swing checker name
#--swing_checker_name="Swing"

# default localization item code
# --swing_item_code=6000001

# default filter: 3/3
# --latency_filter_required_cycles=3
# --latency_filter_total_cycles=3

# default fault removed secs
# --latency_removed_secs=10

# only check swing in auto driving mode
#--swing_check_in_auto_mode=true

# 检查过去多少秒内的数据
#--swing_check_secs=12

# 判断为画龙异常需要的边数量
#--error_swing_count=3

# 按多大角度步长提取点
#--swing_point_extract_deg_threshold=0.2

# 判断是否是有效画龙浮动的阈值，为了防止抖动误判
#--swing_edge_valid_deg_threshold=2.0

# 判断画龙浮动的角度阈值
# --swing_edge_deg_threshold=4.5

# 画龙检测的最小定位数据数量
# --min_loc_point_num=500