--flagfile=/apollo/modules/planning/planning_component/conf/planning.conf
--map_dir=/apollo/modules/map/data/yunle_indoor_map03_planning
--base_map_filename=base_map.bin|base_map.txt
--planning_upper_speed_limit=0.500
--default_cruise_speed=0.500
--destination_check_distance=20.0
