load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "editor_map_proto",
    srcs = ["editor_map.proto"],
)

proto_library(
    name = "map_validator_proto",
    srcs = ["map_validator.proto"],
)

apollo_package()
