# localization shake checker name
#--localization_shake_checker_name="Localization Shake"

# default localization item code
# --localization_distance_shake_code=3005005
# --localization_heading_shake_code=3005006
# --localization_lateral_shake_code=3005007

# only check shake in auto driving mode
#--localization_shake_check_in_auto_mode=true

# default timeout in seconds
#--localization_shake_timeout_secs=10

# distance shake
# warn shake distance limit in meters
#--localization_shake_warn_distance=0.3
# error shake distance limit in meters
#--localization_shake_error_distance=0.5

# heading shake warning degree
#--heading_shake_warn_deg=20
# heading shake error degree
#--heading_shake_error_deg=30


# localization lateral error
# 静止状态定义
#--stationary_speed_threshold=0.01

# 静止时定位侧向速度阈值
#--stationary_localization_lateral_velocity_threshold=0.5

# 车辆直行状态定义
#--straight_steer_percentage_threshold=3

# 车辆直行定位侧向速度阈值
#--straight_localization_lateral_velocity_threshold=0.5

# 定位侧向速度最大阈值
#--localization_lateral_velocity_up_limit=1.5

# 侧向速度容忍阈值，当定位和底盘侧向速度都在这个阈值内豁免
#--lateral_velocity_down_threshold=0.15

# 定位和底盘侧向速度差值阈值
#--lateral_velocity_diff_threshold=1.0

# 连续几次侧向速度异常才报警
#--lateral_error_count_threshold=2

# 前轮转角和定位中心位置移动的比例 (通常用这个默认值就行)
#--wheelbase_factor=0.5

# 检查间隔（通常用这个默认值就行）
#--lateral_check_interval_sec=0.1