--routing_conf_file=/apollo/modules/routing/conf/routing_config.pb.txt
--map_dir=/apollo/modules/map/data/yunle_indoor_map03_planning
--base_map_filename=base_map.bin|base_map.txt
--routing_map_filename=routing_map.bin|routing_map.txt
--routing_response_topic=/apollo/raw_routing_response
--routing_response_history_topic=/apollo/raw_rrouting_response_history
